<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED><!ATTLIST buffer-attribute name CDATA #REQUIRED>]><context name="xml" description="Linux (none) 4.19.0-g3ebdb0e89e11-dirty #70 SMP PREEMPT Tue Sep 1 17:11:43 EEST 2020 armv7l" ><context-attribute name="hw_model" value="Analog Devices M2k Rev.D (Z7010)" /><context-attribute name="hw_model_variant" value="0" /><context-attribute name="hw_serial" value="104473ce6991000bebff1d00058f89ea2f" /><context-attribute name="fw_version" value="v0.25-dirty" /><context-attribute name="cal,offset_pos_dac" value="-0.0107" /><context-attribute name="cal,gain_pos_dac" value="1.00583" /><context-attribute name="cal,offset_pos_adc" value="-0.000264591" /><context-attribute name="cal,gain_pos_adc" value="0.995356" /><context-attribute name="cal,offset_neg_dac" value="-0.0077" /><context-attribute name="cal,gain_neg_dac" value="1.00509" /><context-attribute name="cal,offset_neg_adc" value="-0.00165287" /><context-attribute name="cal,gain_neg_adc" value="0.99642" /><context-attribute name="local,kernel" value="4.19.0-g3ebdb0e89e11-dirty" /><context-attribute name="uri" value="local:" /><device id="iio:device0" name="m2k-adc" ><channel id="voltage0" type="input" ><scan-element index="0" format="le:s12/16&gt;&gt;0" /><attribute name="calibbias" filename="in_voltage0_calibbias" /><attribute name="calibscale" filename="in_voltage0_calibscale" /></channel><channel id="voltage1" type="input" ><scan-element index="1" format="le:s12/16&gt;&gt;0" /><attribute name="calibbias" filename="in_voltage1_calibbias" /><attribute name="calibscale" filename="in_voltage1_calibscale" /></channel><attribute name="oversampling_ratio" /><attribute name="sampling_frequency" /><attribute name="sampling_frequency_available" /><buffer-attribute name="data_available" /><buffer-attribute name="length_align_bytes" /><buffer-attribute name="watermark" /><debug-attribute name="direct_reg_access" /></device><device id="iio:device1" name="xadc" ><channel id="voltage5" name="vccoddr" type="input" ><attribute name="raw" filename="in_voltage5_vccoddr_raw" /><attribute name="scale" filename="in_voltage5_vccoddr_scale" /></channel><channel id="voltage0" name="vccint" type="input" ><attribute name="raw" filename="in_voltage0_vccint_raw" /><attribute name="scale" filename="in_voltage0_vccint_scale" /></channel><channel id="voltage4" name="vccpaux" type="input" ><attribute name="raw" filename="in_voltage4_vccpaux_raw" /><attribute name="scale" filename="in_voltage4_vccpaux_scale" /></channel><channel id="temp0" type="input" ><attribute name="offset" filename="in_temp0_offset" /><attribute name="raw" filename="in_temp0_raw" /><attribute name="scale" filename="in_temp0_scale" /></channel><channel id="voltage7" name="vrefn" type="input" ><attribute name="raw" filename="in_voltage7_vrefn_raw" /><attribute name="scale" filename="in_voltage7_vrefn_scale" /></channel><channel id="voltage1" name="vccaux" type="input" ><attribute name="raw" filename="in_voltage1_vccaux_raw" /><attribute name="scale" filename="in_voltage1_vccaux_scale" /></channel><channel id="voltage2" name="vccbram" type="input" ><attribute name="raw" filename="in_voltage2_vccbram_raw" /><attribute name="scale" filename="in_voltage2_vccbram_scale" /></channel><channel id="voltage3" name="vccpint" type="input" ><attribute name="raw" filename="in_voltage3_vccpint_raw" /><attribute name="scale" filename="in_voltage3_vccpint_scale" /></channel><channel id="voltage8" type="input" ><attribute name="raw" filename="in_voltage8_raw" /><attribute name="scale" filename="in_voltage8_scale" /></channel><channel id="voltage6" name="vrefp" type="input" ><attribute name="raw" filename="in_voltage6_vrefp_raw" /><attribute name="scale" filename="in_voltage6_vrefp_scale" /></channel><attribute name="sampling_frequency" /></device><device id="iio:device10" name="m2k-logic-analyzer-rx" ><channel id="voltage0" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;0" /><attribute name="trigger" filename="in_voltage0_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage1" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;1" /><attribute name="trigger" filename="in_voltage1_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage2" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;2" /><attribute name="trigger" filename="in_voltage2_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage3" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;3" /><attribute name="trigger" filename="in_voltage3_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage4" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;4" /><attribute name="trigger" filename="in_voltage4_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage5" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;5" /><attribute name="trigger" filename="in_voltage5_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage6" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;6" /><attribute name="trigger" filename="in_voltage6_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage7" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;7" /><attribute name="trigger" filename="in_voltage7_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage8" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;8" /><attribute name="trigger" filename="in_voltage8_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage9" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;9" /><attribute name="trigger" filename="in_voltage9_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage10" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;10" /><attribute name="trigger" filename="in_voltage10_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage11" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;11" /><attribute name="trigger" filename="in_voltage11_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage12" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;12" /><attribute name="trigger" filename="in_voltage12_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage13" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;13" /><attribute name="trigger" filename="in_voltage13_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage14" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;14" /><attribute name="trigger" filename="in_voltage14_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage15" type="input" ><scan-element index="0" format="le:u1/16&gt;&gt;15" /><attribute name="trigger" filename="in_voltage15_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage16" type="input" ><attribute name="trigger" filename="in_voltage16_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><channel id="voltage17" type="input" ><attribute name="trigger" filename="in_voltage17_trigger" /><attribute name="trigger_available" filename="in_voltage_trigger_available" /><attribute name="trigger_delay" filename="in_voltage_trigger_delay" /><attribute name="trigger_logic_mode" filename="in_voltage_trigger_logic_mode" /><attribute name="trigger_logic_mode_available" filename="in_voltage_trigger_logic_mode_available" /><attribute name="trigger_mux_out" filename="in_voltage_trigger_mux_out" /><attribute name="trigger_mux_out_available" filename="in_voltage_trigger_mux_out_available" /></channel><attribute name="data_delay_auto" /><attribute name="data_delay_auto_available" /><attribute name="data_in_delay" /><attribute name="rate_mux" /><attribute name="rate_mux_available" /><attribute name="sampling_frequency" /><attribute name="streaming" /><attribute name="triggered" /><buffer-attribute name="data_available" /><buffer-attribute name="length_align_bytes" /><buffer-attribute name="watermark" /></device><device id="iio:device11" name="m2k-fabric" ><channel id="voltage0" type="input" ><attribute name="gain" filename="in_voltage0_gain" /><attribute name="gain_available" filename="in_voltage_gain_available" /><attribute name="powerdown" filename="in_voltage_powerdown" /></channel><channel id="voltage0" type="output" ><attribute name="powerdown" filename="out_voltage0_powerdown" /></channel><channel id="voltage3" type="output" ><attribute name="user_supply_powerdown" filename="out_voltage3_user_supply_powerdown" /></channel><channel id="voltage4" type="output" ><attribute name="done_led_overwrite_powerdown" filename="out_voltage4_done_led_overwrite_powerdown" /></channel><channel id="voltage1" type="output" ><attribute name="powerdown" filename="out_voltage1_powerdown" /></channel><channel id="voltage2" type="output" ><attribute name="user_supply_powerdown" filename="out_voltage2_user_supply_powerdown" /></channel><channel id="voltage1" type="input" ><attribute name="gain" filename="in_voltage1_gain" /><attribute name="gain_available" filename="in_voltage_gain_available" /><attribute name="powerdown" filename="in_voltage_powerdown" /></channel><attribute name="calibration_mode" /><attribute name="calibration_mode_available" /><attribute name="clk_powerdown" /></device><device id="iio:device12" name="m2k-adc-trigger" ><channel id="voltage4" name="trigger_logic" type="input" ><attribute name="mode" filename="in_voltage4_trigger_logic_mode" /><attribute name="mode_available" filename="in_voltage4_trigger_logic_mode_available" /><attribute name="out_direction" filename="in_voltage4_trigger_logic_out_direction" /><attribute name="out_direction_available" filename="in_voltage4_trigger_logic_out_direction_available" /><attribute name="out_hold_pins_raw" filename="in_voltage4_trigger_logic_out_hold_pins_raw" /><attribute name="out_select" filename="in_voltage4_trigger_logic_out_select" /><attribute name="out_select_available" filename="in_voltage4_trigger_logic_out_select_available" /></channel><channel id="voltage5" name="trigger_logic" type="input" ><attribute name="mode" filename="in_voltage5_trigger_logic_mode" /><attribute name="mode_available" filename="in_voltage5_trigger_logic_mode_available" /><attribute name="out_direction" filename="in_voltage5_trigger_logic_out_direction" /><attribute name="out_direction_available" filename="in_voltage5_trigger_logic_out_direction_available" /><attribute name="out_hold_pins_raw" filename="in_voltage5_trigger_logic_out_hold_pins_raw" /><attribute name="out_select" filename="in_voltage5_trigger_logic_out_select" /><attribute name="out_select_available" filename="in_voltage5_trigger_logic_out_select_available" /></channel><channel id="voltage1" type="input" ><attribute name="trigger" filename="in_voltage1_trigger" /><attribute name="trigger_available" filename="in_voltage1_trigger_available" /><attribute name="trigger_hysteresis" filename="in_voltage1_trigger_hysteresis" /><attribute name="trigger_level" filename="in_voltage1_trigger_level" /></channel><channel id="voltage6" name="trigger" type="input" ><attribute name="delay" filename="in_voltage6_trigger_delay" /><attribute name="embedded" filename="in_voltage6_trigger_embedded" /><attribute name="logic_mode" filename="in_voltage6_trigger_logic_mode" /><attribute name="logic_mode_available" filename="in_voltage6_trigger_logic_mode_available" /></channel><channel id="voltage2" type="input" ><attribute name="trigger" filename="in_voltage2_trigger" /><attribute name="trigger_available" filename="in_voltage2_trigger_available" /></channel><channel id="voltage0" type="input" ><attribute name="trigger" filename="in_voltage0_trigger" /><attribute name="trigger_available" filename="in_voltage0_trigger_available" /><attribute name="trigger_hysteresis" filename="in_voltage0_trigger_hysteresis" /><attribute name="trigger_level" filename="in_voltage0_trigger_level" /></channel><channel id="voltage3" type="input" ><attribute name="trigger" filename="in_voltage3_trigger" /><attribute name="trigger_available" filename="in_voltage3_trigger_available" /></channel><attribute name="holdoff_raw" /><attribute name="sampling_frequency" /><attribute name="streaming" /><attribute name="triggered" /><debug-attribute name="direct_reg_access" /></device><device id="iio:device13" name="ad9963" ><channel id="voltage1" type="output" ><attribute name="raw" filename="out_voltage1_raw" /></channel><channel id="temp0" type="input" ><attribute name="offset" filename="in_temp0_offset" /><attribute name="raw" filename="in_temp0_raw" /><attribute name="scale" filename="in_temp0_scale" /></channel><channel id="voltage0" type="input" ><attribute name="raw" filename="in_voltage0_raw" /><attribute name="scale" filename="in_voltage0_scale" /></channel><channel id="voltage3" type="input" ><attribute name="raw" filename="in_voltage3_raw" /><attribute name="scale" filename="in_voltage3_scale" /></channel><channel id="voltage1" type="input" ><attribute name="raw" filename="in_voltage1_raw" /><attribute name="scale" filename="in_voltage1_scale" /></channel><channel id="voltage4" type="input" ><attribute name="raw" filename="in_voltage4_raw" /><attribute name="scale" filename="in_voltage4_scale" /></channel><channel id="voltage5" type="input" ><attribute name="raw" filename="in_voltage5_raw" /><attribute name="scale" filename="in_voltage5_scale" /></channel><channel id="voltage0" type="output" ><attribute name="raw" filename="out_voltage0_raw" /></channel><channel id="voltage2" type="input" ><attribute name="raw" filename="in_voltage2_raw" /><attribute name="scale" filename="in_voltage2_scale" /></channel><debug-attribute name="direct_reg_access" /></device><device id="iio:device2" name="ad5625" ><channel id="voltage1" type="output" ><attribute name="powerdown" filename="out_voltage1_powerdown" /><attribute name="powerdown_mode" filename="out_voltage1_powerdown_mode" /><attribute name="powerdown_mode_available" filename="out_voltage_powerdown_mode_available" /><attribute name="raw" filename="out_voltage1_raw" /><attribute name="scale" filename="out_voltage1_scale" /></channel><channel id="voltage2" type="output" ><attribute name="powerdown" filename="out_voltage2_powerdown" /><attribute name="powerdown_mode" filename="out_voltage2_powerdown_mode" /><attribute name="powerdown_mode_available" filename="out_voltage_powerdown_mode_available" /><attribute name="raw" filename="out_voltage2_raw" /><attribute name="scale" filename="out_voltage2_scale" /></channel><channel id="voltage0" type="output" ><attribute name="powerdown" filename="out_voltage0_powerdown" /><attribute name="powerdown_mode" filename="out_voltage0_powerdown_mode" /><attribute name="powerdown_mode_available" filename="out_voltage_powerdown_mode_available" /><attribute name="raw" filename="out_voltage0_raw" /><attribute name="scale" filename="out_voltage0_scale" /></channel><channel id="voltage3" type="output" ><attribute name="powerdown" filename="out_voltage3_powerdown" /><attribute name="powerdown_mode" filename="out_voltage3_powerdown_mode" /><attribute name="powerdown_mode_available" filename="out_voltage_powerdown_mode_available" /><attribute name="raw" filename="out_voltage3_raw" /><attribute name="scale" filename="out_voltage3_scale" /></channel></device><device id="iio:device3" name="ad5627" ><channel id="voltage1" type="output" ><attribute name="powerdown" filename="out_voltage1_powerdown" /><attribute name="powerdown_mode" filename="out_voltage1_powerdown_mode" /><attribute name="powerdown_mode_available" filename="out_voltage_powerdown_mode_available" /><attribute name="raw" filename="out_voltage1_raw" /><attribute name="scale" filename="out_voltage1_scale" /></channel><channel id="voltage0" type="output" ><attribute name="powerdown" filename="out_voltage0_powerdown" /><attribute name="powerdown_mode" filename="out_voltage0_powerdown_mode" /><attribute name="powerdown_mode_available" filename="out_voltage_powerdown_mode_available" /><attribute name="raw" filename="out_voltage0_raw" /><attribute name="scale" filename="out_voltage0_scale" /></channel></device><device id="iio:device4" name="pll" ><channel id="altvoltage0" type="output" ><attribute name="frequency" filename="out_altvoltage0_frequency" /><attribute name="mute_till_lock_detect" filename="out_altvoltage0_mute_till_lock_detect" /><attribute name="muxout_mode" filename="out_altvoltage0_muxout_mode" /><attribute name="muxout_mode_available" filename="out_altvoltage_muxout_mode_available" /><attribute name="pfd_frequency" filename="out_altvoltage0_pfd_frequency" /><attribute name="power_down" filename="out_altvoltage0_power_down" /><attribute name="power_down_available" filename="out_altvoltage_power_down_available" /><attribute name="power_level" filename="out_altvoltage0_power_level" /><attribute name="power_level_available" filename="out_altvoltage_power_level_available" /><attribute name="refin_frequency" filename="out_altvoltage0_refin_frequency" /></channel><debug-attribute name="direct_reg_access" /></device><device id="iio:device5" name="m2k-dds" ><channel id="altvoltage3" name="2B" type="output" ><attribute name="frequency" filename="out_altvoltage3_2B_frequency" /><attribute name="phase" filename="out_altvoltage3_2B_phase" /><attribute name="raw" filename="out_altvoltage3_2B_raw" /><attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" /><attribute name="scale" filename="out_altvoltage3_2B_scale" /></channel><channel id="altvoltage0" name="1A" type="output" ><attribute name="frequency" filename="out_altvoltage0_1A_frequency" /><attribute name="phase" filename="out_altvoltage0_1A_phase" /><attribute name="raw" filename="out_altvoltage0_1A_raw" /><attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" /><attribute name="scale" filename="out_altvoltage0_1A_scale" /></channel><channel id="altvoltage1" name="1B" type="output" ><attribute name="frequency" filename="out_altvoltage1_1B_frequency" /><attribute name="phase" filename="out_altvoltage1_1B_phase" /><attribute name="raw" filename="out_altvoltage1_1B_raw" /><attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" /><attribute name="scale" filename="out_altvoltage1_1B_scale" /></channel><channel id="altvoltage2" name="2A" type="output" ><attribute name="frequency" filename="out_altvoltage2_2A_frequency" /><attribute name="phase" filename="out_altvoltage2_2A_phase" /><attribute name="raw" filename="out_altvoltage2_2A_raw" /><attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" /><attribute name="scale" filename="out_altvoltage2_2A_scale" /></channel><debug-attribute name="direct_reg_access" /></device><device id="iio:device6" name="m2k-dac-a" ><channel id="voltage0" type="output" ><scan-element index="0" format="le:S16/16&gt;&gt;0" /></channel><attribute name="calibscale" /><attribute name="dma_sync" /><attribute name="dma_sync_start" /><attribute name="oversampling_ratio" /><attribute name="sampling_frequency" /><attribute name="sampling_frequency_available" /><attribute name="trigger_condition" /><attribute name="trigger_condition_available" /><attribute name="trigger_src" /><attribute name="trigger_src_available" /><buffer-attribute name="data_available" /><buffer-attribute name="length_align_bytes" /><buffer-attribute name="watermark" /><debug-attribute name="direct_reg_access" /></device><device id="iio:device7" name="m2k-dac-b" ><channel id="voltage0" type="output" ><scan-element index="0" format="le:S16/16&gt;&gt;0" /></channel><attribute name="calibscale" /><attribute name="dma_sync" /><attribute name="dma_sync_start" /><attribute name="oversampling_ratio" /><attribute name="sampling_frequency" /><attribute name="sampling_frequency_available" /><attribute name="trigger_condition" /><attribute name="trigger_condition_available" /><attribute name="trigger_src" /><attribute name="trigger_src_available" /><buffer-attribute name="data_available" /><buffer-attribute name="length_align_bytes" /><buffer-attribute name="watermark" /><debug-attribute name="direct_reg_access" /></device><device id="iio:device8" name="m2k-logic-analyzer" ><channel id="voltage6" type="input" ><attribute name="direction" filename="in_voltage6_direction" /><attribute name="direction_available" filename="in_voltage_direction_available" /><attribute name="outputmode" filename="in_voltage6_outputmode" /><attribute name="outputmode_available" filename="in_voltage_outputmode_available" /><attribute name="raw" filename="in_voltage6_raw" /></channel><channel id="voltage3" type="input" ><attribute name="direction" filename="in_voltage3_direction" /><attribute name="direction_available" filename="in_voltage_direction_available" /><attribute name="outputmode" filename="in_voltage3_outputmode" /><attribute name="outputmode_available" filename="in_voltage_outputmode_available" /><attribute name="raw" filename="in_voltage3_raw" /></channel><channel id="voltage8" type="input" ><attribute name="direction" filename="in_voltage8_direction" /><attribute name="direction_available" filename="in_voltage_direction_available" /><attribute name="outpu